import type { Metadata } from "next";
import "./globals.css";
import Foot from "@/components/Foot";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Header />
        </nav>

        <main>{children}</main>

        <Foot />
      </body>
    </html>
  );
}
